language: generic
sudo: required
services:
  - docker

before_install: 
#  - openssl aes-256-cbc -K $encrypted_0c35eebf403c_key -iv $encrypted_0c35eebf403c_iv -in not-auth-file.json.enc -out not-auth-file.json -d
#  - curl https://sdk.cloud.google.com | bash >/dev/null;
#  - source $HOME/google-cloud-sdk/path.bash.inc
#  - gcloud components update kubectl
#  - gcloud auth active-services-account --key-file service-account.json
#  - gcloud config set project skilful-berm-214822
#  - gcloud config set compute/zone us-central1-a
#  - gcloud container cluster get-credentials kubernetes-fib

  - docker build -t don2001l/kubernetes-fib -f ./client/Dockerfile.dev ./client


script:
  - docker run -e CI=true don2001l/kubernetes-fib npm run test -- --coverage

after_success:
deploy: 
  provider: script
  script: bash ./deploy.sh 
  on: 
    branch:master

# Login to Docker HUB
  - echo "$DOCKER_AUTO" | docker login -u "$DOCKER_ID" --password-stdin

# push to Docker HUB 
  - docker push don2001l/kubernetes-fib-client
  - docker push don2001l/kubernetes-fib-nginx
  - docker push don2001l/kubernetes-fib-server
  - docker push don2001l/kubernetes-fib-worker

# Push to AWS
#deploy:
#  edge: true
#  provider: elasticbeanstalk
#  region: "us-east-2"
#  app: "multi-docker"
#  env: "MultiDocker-env"
#  bucket_name: elasticbeanstalk-us-east-2-693759577295
#  bucket_path: "multi-docker"
#  on:
#    branch: master
#  access_key_id: "$AWS_ACCESS_KEY"
#  secret_access_key: "$AWS_SECRET_KEY"
